### ISSUE TITLE
Occasional TypeError on NoneType

### ISSUE THREAD

**Issue by mctinker** [leftmove/cria#8]
This only occurs occasionally, and I don't see anything wrong on my end...
Traceback (most recent call last):
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/main.py", line 40, in <module>
    main()
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/main.py", line 21, in main
    return_code = mapit.mapit_all("")
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapit.py", line 716, in mapit_all
    do_rerun()
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapit.py", line 558, in do_rerun
    restart_program()
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapit.py", line 537, in restart_program
    _ = mapit_all("")
        ^^^^^^^^^^^^^
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapit.py", line 702, in mapit_all
    map_ai()
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapai.py", line 283, in map_ai
    local_ai(query, ai_object, item)
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapai.py", line 109, in local_ai
    with cria.Model(PrimeItems.program_arguments["ai_model"]) as ai:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikrubin/Library/Caches/pypoetry/virtualenvs/maptasker-DP8Ceg2U-py3.12/lib/python3.12/site-packages/cria.py", line 280, in __init__
    super().__init__(
  File "/Users/mikrubin/Library/Caches/pypoetry/virtualenvs/maptasker-DP8Ceg2U-py3.12/lib/python3.12/site-packages/cria.py", line 194, in __init__
    ollama_process = find_process(["ollama", "serve"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikrubin/Library/Caches/pypoetry/virtualenvs/maptasker-DP8Ceg2U-py3.12/lib/python3.12/site-packages/cria.py", line 168, in find_process
    if proc_command[: len(command)] != command:
       ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by mctinker** [comment]
The query was...
"Given the following Profile in Tasker, an Android automation tool, how could it be improved for performance and readibility: (Tasker Profile here)"
Python 3.12.4
OS X 14.6.1
Cria 1.6.6

**Comment by mctinker** [comment]
The fix: 
In function "find_process", modify the line...
`if process_name.lower() in proc.name().lower():`
...to...
`if process_name.lower() in proc.name().lower() and proc.info["cmdline"] is not None:`
