### ISSUE TITLE
Recursive calls gives: "TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by mctinker** [leftmove/cria#9]
When invoking cria a second or more times from within the same Python program using a local model (llama3.1/gemma/etc.), it throws an error:
 
Traceback (most recent call last):
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/main.py", line 40, in <module>
    main()
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/main.py", line 21, in main
    return_code = mapit.mapit_all("")
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapit.py", line 729, in mapit_all
    do_rerun()
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapit.py", line 571, in do_rerun
    restart_program()
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapit.py", line 550, in restart_program
    _ = mapit_all("")
        ^^^^^^^^^^^^^
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapit.py", line 715, in mapit_all
    map_ai()
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapai.py", line 298, in map_ai
    local_ai(query, ai_object, item)
  File "/Users/mikrubin/Library/CloudStorage/GoogleDrive-mikrubin@gmail.com/My Drive/Python/maptasker/maptasker/src/mapai.py", line 123, in local_ai
    with cria.Model(PrimeItems.program_arguments["ai_model"]) as ai:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikrubin/Library/Caches/pypoetry/virtualenvs/maptasker-DP8Ceg2U-py3.12/lib/python3.12/site-packages/cria.py", line 280, in __init__
    super().__init__(
  File "/Users/mikrubin/Library/Caches/pypoetry/virtualenvs/maptasker-DP8Ceg2U-py3.12/lib/python3.12/site-packages/cria.py", line 194, in __init__
    ollama_process = find_process(["ollama", "serve"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikrubin/Library/Caches/pypoetry/virtualenvs/maptasker-DP8Ceg2U-py3.12/lib/python3.12/site-packages/cria.py", line 168, in find_process
    if proc_command[: len(command)] != command:
       ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Python 3.12.4
OS X 14.6.1
Cria 1.6.6
Ollama 0.3.10

Here is the code used:

`prompt  = query.split(":")[0]  # Skip the first character, which is a colon.
    context = query.replace(prompt[1:], "")  # All of the Project/Profile/Task data
    messages = [
        {
            "role": "system",
            "content": f"You are a programmer using Tasker, and Android task management tool. The program code follows, with each line separated by '\n'. {prompt}:{context}",
        },
        {"role": "user", "content": context},
    ]
    response = ""

    # Open the model and get the response
    try:
        with cria.Model(PrimeItems.program_arguments["ai_model"]) as ai:
            for chunk in ai.chat(messages=messages, prompt=prompt):
                response = f"{response}{chunk}"
            ai.clear()

        # Open error file, since we're going to queue up the response in this file for display back to the GUI.
        record_response(response, ai_object, item)

    except (FileNotFoundError, ValueError, TypeError, UnboundLocalError) as e:
        if "NoneType" in str(e):
            error_handler("A program error has occurred.  Exit MapTasker and rerun it again to clear the error.", 12)
        else:
            error_handler(
                f"Ai analysis error: {e}.  Try again.",
                12,
            )`

It fails regardless of the local model used.

Here is the 'prompt':
'Given the following Task in Tasker, an Android automation tool, suggest improvements for performance and readability'

Here is the 'message':
[{'role': 'system', 'content': "You are a programmer using Tasker, and Android task management tool. The program code follows, with each line separated by '\n'. Given the following Task in Tasker, an Android automation tool, suggest improvements for performance and readability:G:Project: Adaptive Brightness Quick Setting\nProfile: None or unnamed!\n\n\nTask: Ad Brg  (Not referenced by any Profile in Project 'Adaptive Brightness Quick Setting')   [Priority: 100]  [Icon Info(name=mw_device_brightness_auto)]\nAction: 01 Custom Settings  Test=System, Name=screen_brightness_mode, Value==:=toggle=:=  \n"}, {'role': 'user', 'content': "G:Project: Adaptive Brightness Quick Setting\nProfile: None or unnamed!\n\n\nTask: Ad Brg  (Not referenced by any Profile in Project 'Adaptive Brightness Quick Setting')   [Priority: 100]  [Icon Info(name=mw_device_brightness_auto)]\nAction: 01 Custom Settings  Test=System, Name=screen_brightness_mode, Value==:=toggle=:=  \n"}]

Any assistance would be greatly appreciated!

**Comment by mctinker** [comment]
The fix: 
In function "find_process", modify the line...
`if process_name.lower() in proc.name().lower():`
...to...
`if process_name.lower() in proc.name().lower() and proc.info["cmdline"] is not None:`
